Controllers/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MoneyTransfer.Models;
using MoneyTransfer.Services.Interface;

namespace MoneyTransfer.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {

        private readonly ITransactionDetails transactionDetails;
        private readonly IBankAccount bankAccount;
        private readonly UserManager<User> userManager;
        public ReportController(IBankAccount bankAccount,ITransactionDetails transactionDetails,UserManager<User> userManager)
        {
            this.bankAccount = bankAccount;
            this.transactionDetails = transactionDetails;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
           
            var currentuser = userManager.GetUserId(User);
            var TransactionDetails = await transactionDetails.GetAll(it => it.Id == currentuser);
            var BankAccountDetails = await bankAccount.GetAll();
            var list = new List<ReportModel>();
            foreach (var items in TransactionDetails)
            {
                var Model = new ReportModel();
                Model.SenderBankName = items.senderBankName;
                Model.SenderAcctNo = items.senderBankAccNo;
                Model.TransferAmount = items.transferAmt;
                Model.PayoutAmount = items.PayoutAmt;
                Model.TransactionDate = items.transactionDate;
                Model.ReceiverBankName = items.ReceiverBankName;
                Model.ReceiverAcctNo = items.ReceiverBankAccNo;
                var SenderBankAcc = BankAccountDetails.Where(it => it.AccountNumber == items.senderBankAccNo).FirstOrDefault();
                var ReceiverBankAcc = BankAccountDetails.Where(it => it.AccountNumber == items.ReceiverBankAccNo).FirstOrDefault();
                if (SenderBankAcc != null)
                {
                    var SenderDetailsModel = new SenderDetails
                    {
                        FirstName = SenderBankAcc.FirstName,
                        LastName = SenderBankAcc.LastName,
                        Country = SenderBankAcc.Country,
                        Address = SenderBankAcc.Address
                    };
                    Model.SenderDetails = SenderDetailsModel;
                }
                if (ReceiverBankAcc != null)
                {
                    var ReceiverDetailsModel = new ReceiverDetails
                    {
                        FirstName = ReceiverBankAcc.FirstName,
                        LastName = ReceiverBankAcc.LastName,
                        Country = ReceiverBankAcc.Country,
                        Address = ReceiverBankAcc.Address
                    };
                    Model.ReceiverDetails = ReceiverDetailsModel;
                }
                list.Add(Model);
            }
            return View(list);
        }
        [HttpPost]
        public async Task<IActionResult> Index(DateTime fromdate,DateTime toDate)
        {
            ViewBag.fromDate = fromdate.Date.ToString("yyyy-MM-dd");
            ViewBag.toDate = toDate.Date.ToString("yyyy-MM-dd");
            var currentuser = userManager.GetUserId(User);
            var TransactionDetails = await transactionDetails.GetAll(it => it.Id == currentuser && it.transactionDate.Date >= fromdate.Date && 
            it.transactionDate.Date <= toDate.Date);
            var BankAccountDetails = await bankAccount.GetAll();
            var list = new List<ReportModel>();
            foreach (var items in TransactionDetails)
            {
                var Model = new ReportModel();
                Model.SenderBankName = items.senderBankName;
                Model.SenderAcctNo = items.senderBankAccNo;
                Model.TransferAmount = items.transferAmt;
                Model.PayoutAmount = items.PayoutAmt;
                Model.TransactionDate = items.transactionDate;
                var SenderBankAcc = BankAccountDetails.Where(it => it.AccountNumber == items.senderBankAccNo).FirstOrDefault();
                var ReceiverBankAcc = BankAccountDetails.Where(it => it.AccountNumber == items.ReceiverBankAccNo).FirstOrDefault();
                if (SenderBankAcc != null)
                {
                    var SenderDetailsModel = new SenderDetails
                    {
                        FirstName = SenderBankAcc.FirstName,
                        LastName = SenderBankAcc.LastName,
                        Address = SenderBankAcc.Address
                    };
                    Model.SenderDetails = SenderDetailsModel;
                }

                if (ReceiverBankAcc != null)
                {
                    var ReceiverDetailsModel = new ReceiverDetails
                    {
                        FirstName = ReceiverBankAcc.FirstName,
                        LastName = ReceiverBankAcc.LastName,
                        Address = ReceiverBankAcc.Address
                    };
                    Model.ReceiverDetails = ReceiverDetailsModel;
                }
                list.Add(Model);
            }
            return View(list);
        }

    }
}

Controllers/TransferController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MoneyTransfer.Models;
using MoneyTransfer.Services.Interface;
using MoneyTransfer.ViewModels;
using System.Xml;

namespace MoneyTransfer.Controllers
{
    [Authorize]
    public class TransferController : Controller
    {
        private readonly IBankDetails bankDetails;
        private readonly IBankAccount bankAccount;
        private readonly ITransactionDetails transactionDetails;
        private readonly UserManager<User> userManager;
        private readonly IApiService apiService;

        public TransferController(IBankDetails bankDetails,IBankAccount bankAccount, ITransactionDetails transactionDetails,UserManager<User> userManager,IApiService apiService)
        {
            this.bankDetails = bankDetails;
            this.bankAccount = bankAccount;
            this.transactionDetails = transactionDetails;
            this.userManager = userManager;
            this.apiService = apiService;
        }
        public async Task<IActionResult> Index()
        {
            var fromBankList = await bankDetails.GetAll(it => it.IsoCode == "MYR");
            var toBankList = await bankDetails.GetAll(it => it.IsoCode == "NPR");
            TransferVM transferVM = new TransferVM();
            transferVM.fromCurrency = "MYR";
            transferVM.toCurrency = "NPR";
            foreach (var bank in fromBankList) 
            {
                transferVM.senderBankList.Add(new SelectListItem { Value = bank.BankId.ToString(), Text = $"{bank.BankName}" });
            
            }

            foreach (var bank in toBankList)
            {
                transferVM.receiverBankList.Add(new SelectListItem { Value = bank.BankId.ToString(), Text = $"{bank.BankName}" });

            }
            var datas = await apiService.GetDatas(DateTime.Now.ToString("yyyy-MM-dd").ToString(), DateTime.Now.ToString("yyyy-MM-dd").ToString());
            var exchangeRate = datas.Data.Payload.SelectMany(it => it.Rates) .FirstOrDefault(rate => rate.Currency.Iso3 == "MYR");
            ViewBag.ExchangeRate = exchangeRate != null ? $" {exchangeRate.Currency.Unit} NPR =  {exchangeRate.Buy} {exchangeRate.Currency.Iso3}" : string.Empty; 
            return View(transferVM);
        }
        [HttpPost]
        public async Task<IActionResult> Index(TransferVM transferVM,string ExchangeRate)
        {
            var fromBankList = await bankDetails.GetAll(it => it.IsoCode == "MYR");
            var toBankList = await bankDetails.GetAll(it => it.IsoCode == "NPR");
            foreach (var bank in fromBankList)
            {
                transferVM.senderBankList.Add(new SelectListItem { Value = bank.BankId.ToString(), Text = $"{bank.BankName}" });

            }

            foreach (var bank in toBankList)
            {
                transferVM.receiverBankList.Add(new SelectListItem { Value = bank.BankId.ToString(), Text = $"{bank.BankName}" });

            }
            var datas = await apiService.GetDatas(DateTime.Now.ToString("yyyy-MM-dd").ToString(), DateTime.Now.ToString("yyyy-MM-dd").ToString());
            var exchangeRate = datas.Data.Payload.SelectMany(it => it.Rates).FirstOrDefault(rate => rate.Currency.Iso3 == "MYR");
            ViewBag.ExchangeRate = exchangeRate != null ? $" {exchangeRate.Currency.Unit} NPR =  {exchangeRate.Buy} {exchangeRate.Currency.Iso3}" : string.Empty;
            if (!ModelState.IsValid)
                return View(transferVM);
            var fromBankAcc = await bankAccount.Get(it => it.AccountNumber == transferVM.senderBankAccNo && it.BankId == Int32.Parse(transferVM.senderBankName));
            if(fromBankAcc == null)
            {
                ModelState.AddModelError(string.Empty, $"Invalid Bank Acc No {transferVM.senderBankAccNo}");
                return View(transferVM);
            }
            var toBankAcc = await bankAccount.Get(it => it.AccountNumber == transferVM.receiverBankAccNo && it.BankId == Int32.Parse(transferVM.receiverBankName));
            if(toBankAcc == null)
            {
                ModelState.AddModelError(string.Empty, $"Invalid Bank Acc No {transferVM.senderBankAccNo}");
                return View(transferVM);
            }
            if (fromBankAcc.Balance < transferVM.transferAmt)
            {
                ModelState.AddModelError(string.Empty, $"Insufficient Balance for Acct No {transferVM.senderBankAccNo}");
            }
            TransactionDetails Models = new TransactionDetails
            {
                transactionDate = DateTime.Now,
                senderBankName = transferVM.senderBankName,
                senderBankAccNo = transferVM.senderBankAccNo,
                transferAmt = transferVM.transferAmt,
                ReceiverBankName = transferVM.receiverBankName,
                ReceiverBankAccNo = transferVM.receiverBankAccNo,
                ExchangeRate    = ExchangeRate,
                PayoutAmt = transferVM.amtToBeReceived,
                Id = userManager.GetUserId(User)
            };
            fromBankAcc.Balance -=  transferVM.transferAmt;
            toBankAcc.Balance += transferVM.transferAmt;
            await transactionDetails.Add(Models);
            await bankAccount.Update(fromBankAcc);
            await bankAccount.Update(toBankAcc);
            try
            {
                await transactionDetails.SaveAsync();
                await bankAccount.SaveAsync();
                TempData["Success"] = "Transaction Success";
            }
            catch (Exception ex) 
            {
                Console.WriteLine(ex.Message.ToString());
                TempData["Error"] = "Transaction Failes";
            }
            return RedirectToAction("Index", "Dashboard");

        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoneyTransfer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoneyTransfer.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">MoneyTransfer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Dashboard" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Transfer" asp-action="Index">Transfer Money</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Report" asp-action="Index">Generate Report</a>
                            </li>
                        }
                    </ul>
                    <partial name="_loginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-center">
            &copy; 2025 - MoneyTransfer
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
          toastr.options =
          {
          "closeButton": true,
          "debug": false,
          "newestOnTop": true,
          "progressBar": true,
          "positionClass": "toast-bottom-left",
          "preventDuplicates": true,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        };
        @if (TempData["Success"] != null)
        {
            <text>toastr.success('@TempData["Success"]');</text>
        }
        @if (TempData["Error"] != null)
        {
            <text>toastr.error('@TempData["Error"]');</text>
        }
        @if (TempData["Info"] != null)
        {
            <text>toastr.info('@TempData["Error"]');</text>
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>